---
- hosts: master
  tasks:
    - name: Install Go and Make
      become_user: root
      apt: 
        update_cache: yes
        name:
          - golang
          - make

    - name: Download and Compile k9s
      become_user: "{{ ansible_user }}"
      shell: |
        git clone https://github.com/derailed/k9s.git
        cd k9s
        make build -j $(nproc)

    - name: Copy k9s to bin
      become_user: root
      copy:
        src: /home/{{ ansible_user}}/k9s/execs/k9s
        dest: /bin/k9s
        remote_src: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'