---
- hosts: registry
  tasks:
    - name: Run Docker Registry
      become_user: root
      shell: |
        docker run -d -p 5000:5000 --restart=always --name registry registry:2

    - name: Put Nginx in registry
      become_user: root
      shell: |
        docker pull nginx:1.14.2
        docker tag nginx:1.14.2 localhost:5000/my-nginx
        docker push localhost:5000/my-nginx
        docker image remove nginx:1.14.2
        docker image remove localhost:5000/my-nginx
