---
- hosts: all
  tasks:
    - name: Install Kubelet Kubeadm and Kubectl
      become_user: root
      shell: |
        cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        exclude=kubelet kubeadm kubectl
        EOF

        # Set SELinux in permissive mode (effectively disabling it)
        sudo setenforce 0
        sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

        sudo yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
        sudo systemctl enable kubelet
        echo 'KUBELET_EXTRA_ARGS="--fail-swap-on=false"' > /etc/sysconfig/kubelet
        sudo systemctl start kubelet


    - name: Install Containerd
      become_user: root
      shell: |
        dnf install -y yum-utils device-mapper-persistent-data lvm2

        dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
        dnf update -y && dnf install -y containerd.io

        mkdir -p /etc/containerd
        containerd config default > /etc/containerd/config.toml
        systemctl restart containerd
        systemctl enable containerd

    - name: Fix up /run/systemd/resolve
      become_user: root
      shell: |
        ln -sf /run/NetworkManager /run/systemd/resolve