---
- hosts: all
  tasks:
    - name: Update
      dnf:
        name: "*"
        state: latest

    - name: Install Needed Tools
      dnf:
        name: "tar,wget"
        state: latest

    - name: Install Nice to haves
      dnf:
        name: "htop"
        state: latest