---
- hosts: all
  tasks:
    - name: Configure Kubernetes
      become_user: root
      shell: |
        cat <<EOF | sudo tee /etc/modules-load.d/containerd.conf
        overlay
        br_netfilter
        EOF

        modprobe overlay
        modprobe br_netfilter

        cat << EOF | tee /etc/sysctl.d/99-kubernetes-cri.conf
        net.bridge.bridge-nf-call-iptables  = 1
        net.ipv4.ip_forward                 = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        EOF

        sysctl --system

    - name: Create /etc/containerd
      become_user: root
      file:
        path: /etc/containerd
        state: directory
        mode: 0755

    - name: Configure containerd
      become_user: root
      copy:
        src: ../config/containerdconfig.toml
        dest: /etc/containerd/config.toml
        owner: root
        group: root
        mode: '0644'
      # shell: |
      #   containerd config default | tee /etc/containerd/config.toml

    # - name: Enable Network Forwarding
    #   become_user: root
    #   shell: |
    #     echo "net.bridge.bridge-nf-call-iptables=1" | tee -a /etc/sysctl.conf
    #     sysctl -p

- hosts: master
  tasks:
    - name: Change Master Hostname
      become_user: root
      hostname:
        name: "master-{{ play_hosts.index(inventory_hostname)|int+1 }}"
    
    - name: Initialize Cluster (WILL BE SLOW)
      become_user: root
      shell: |
        kubeadm reset -f
        kubeadm init --pod-network-cidr=10.244.0.0/16
        echo "cgroupDriver: systemd" >> /var/lib/kubelet/config.yaml
        echo "resolvConf: /run/systemd/resolve/resolv.conf" >> /var/lib/kubelet/config.yaml
        systemctl restart kubelet

    - name: Create the kube directory
      become_user: "{{ ansible_user }}"
      file:
        path: /home/{{ansible_user}}/.kube
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755

    - name: Copy the admin config
      become_user: root
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ ansible_user }}/.kube/config
        remote_src: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'






