---
- hosts: all
  tasks:
    - name: Copy Modules to Clients
      become_user: root
      copy:
        src: "{{ kernel_pkg }}"
        dest: /lib/modules/
        owner: root
        group: root
        mode: '0644'

    - name: Install Modules
      become_user: root
      shell: |
        mkdir store
        tar xf kernel.tar.gz -C store
        mv store/lib/modules/`uname -r` .
        rm -rf store
      args:
        chdir: /lib/modules/